  export    const suggestGenres = [
    { name: "Action" },
    { name: "Adventure" },
    { name: "Comedy" },
    { name: "Drama" },
    { name: "Fantasy" },
    { name: "Horror" },
    { name: "Mystery" },
    { name: "Romance" },
    { name: "Sci-Fi" },
    { name: "Thriller" },
    { name: "Animation" },
    { name: "Documentary" },
    { name: "Musical" },
    { name: "Western" },
    { name: "Crime" },
    { name: "Family" },
    { name: "Historical" },
    { name: "Superhero" },
    { name: "War" },
    { name: "Biography" },
    { name: "Sports" },
    { name: "Noir" },
    { name: "Spy" },
    { name: "Psychological" },
    { name: "Political" },
    { name: "Satire" },
    { name: "Slice of Life" },
    { name: "Space" },
    { name: "Time Travel" }
      ]